global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kanban API Service
  - job_name: 'kanban-api'
    static_configs:
      - targets: ['backend-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Allocator Agent Service
  - job_name: 'allocator-agent'
    static_configs:
      - targets: ['allocator-agent:8081']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # AI Service
  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-service:8001']  # Metrics port
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 15s

  # Frontend Health
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Infrastructure Services
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']  # Prometheus metrics port
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s
    scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
